### PR TITLE
BYU icons

### PR DESCRIPTION
**Pull request by blakemorgan**
Adds BYU icons created by publication and graphics so they can be used outside of Brightspot.

### CODE REVIEW

**Comment by kevin-larry-bauer** [comment]
LGTM - do you want me to go ahead and merge?

**Comment by blakemorgan** [comment]
@kebowdog If you can give it approval, I can merge it.

**Review by kevin-larry-bauer — APPROVED** [review]
Sorry, for some reason I forgot how to use Git and couldn't find the "Approve" button. :)

**Review by rburkey87 — APPROVED** [review]
LGTM

**Pull request merged**
